[package]
name = "flitton_fib_sjr_rs"
version = "0.1.0"
authors = ["Steve Russo <sjrusso8@gmail.com"]
edition = "2021"

[dependencies]

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]

[lib]
name = "flitton_fib_sjr_rs"
crate-type = ["rlib", "cdylib"]